apiVersion: v1
kind: ServiceAccount
metadata:
  name: dumpstore-backend-sa
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dumpstore-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: dumpstore-backend-app
  template:
    metadata:
      labels:
        app: dumpstore-backend-app
    spec:
      serviceAccountName: dumpstore-backend-sa
      containers:
        - name: dumpstore-backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
          - configMapRef:
              name: dumpstore-backend-configmap
