apiVersion: v1
kind: Service
metadata:
  name: dumpstore-frontend
spec:
  selector:
    app: dumpstore-frontend-app
  ports:
    - port: 5173
      protocol: TCP
      targetPort: 5173
  # type: NodePort