apiVersion: v1
kind: Service
metadata:
  name: dumpstore-backend
spec:
  selector:
    app: dumpstore-backend-app
  ports:
    - port: 3008
      protocol: TCP
      targetPort: 3008
  # type: NodePort