version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - frontend
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/chrome-extension"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - chrome-extension
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - backend
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency]"
