name: helm-release

on:
  pull_request:

# on:
#   push:
#     tags:
#       - 'dumpstore-v*'

permissions:
  contents: write
  packages: write
  id-token: write
  pages: write

jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Lint chart
        run: helm lint ./helm/dumpstore
      - name: Package chart
        run: |
          mkdir -p .dist
          helm package ./helm/dumpstore --destination .dist

      - name: Login to GHCR (OCI)
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GHCR (OCI)
        run: |
          helm push .dist/dumpstore-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts

      - name: Upload to GitHub Pages (static Helm repo)
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          linting: off
          charts_dir: helm

      - name: Publish to ArtifactHub
        run: |
          curl -sSfL https://github.com/artifacthub/hub/releases/latest/download/ah_$(uname -s)_$(uname -m).tar.gz | tar -xz -C /usr/local/bin ah
          ah lint && ah publish
