name: releaser

permissions: {}

on:
  pull_request:

#   push:
#     tags:
#       - v*

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME_BACKEND: dumpstore-backend
  DOCKER_IMAGE_NAME_FRONTEND: dumpstore-frontend
  DOCKERFILE_PATH_BACKEND: ./backend/Dockerfile
  DOCKERFILE_PATH_FRONTEND: ./frontend/Dockerfile
jobs:
  build-push-frontend:
    name: "Build and Push to Docker Registry - frontend"
    runs-on: ubuntu-22.04
    defaults:
        run:
           working-directory: ./frontend
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ${{ env.DOCKERFILE_PATH_FRONTEND }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ github.sha }}


  build-push-backend:
    name: "Build and Push to Docker Registry - Backend"
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ${{ env.DOCKERFILE_PATH_BACKEND }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME_BACKEND }}:${{ github.sha }}
