name: releaser

# on:
#   pull_request:
    
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        service: [backend, frontend]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/dumpstore-${{ matrix.service }}:${{ github.sha }}